### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-static-laptop-setup#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://elite-comb.surge.sh/).

**Comment by chrisvfritz** [comment]
Looks great! :shipit:

**Comment by KatieMFritz** [comment]
How do I make a shipit squirrel?!

**Comment by chrisvfritz** [comment]
Type in `:shipit:` :smile:

**Comment by KatieMFritz** [comment]
:shipit:

**Comment by KatieMFritz** [comment]
dude.
:+1:
